### ISSUE TITLE
adding an option to suffix the file extension

### ISSUE THREAD

**Issue by davidsmorais** [WarrenJones/vite-plugin-require-transform#4] opened 2022-03-22 23:05 UTC
👋  Hey,

Great plugin 👏 , so far, it's the only that's been able to help me migrating from webpack to vite.
I have an auto generated typescript file based on my file structure. This file generates alot of dynamic `require` statements and your plugin so far has been the only one able to properly transpile this.
However, I have most files with duplicates of different extensions, and your plugin breaks when I import files in this condition:

```ts
  const ImagesHudShiftKeyJSON = require("assets/images/hud/shift_key.json").default;
  const ImagesHudShiftKeyPNG = require("assets/images/hud/shift_key.png").default;
  const ImagesHudXKeyJSON = require("assets/images/hud/X_key.json").default;
  const ImagesHudXKeyPNG = require("assets/images/hud/X_key.png").default;
```

**Comment by WarrenJones** [comment] 2022-03-23 02:13
Can you take a screenshot about the error? maybe the error is not about the extensions I think, it's about the format **require(...).default**, let's see what the real problem is and I'm glad to fix it

**Comment by davidsmorais** [comment] 2022-03-23 21:00
Hey 👋 
Thanks for replying.

From what I've seen, this started to happen with `.css` & `.ttf` files with the same name, here's my case: 
![image](https://user-images.githubusercontent.com/22729436/159794294-75c26242-9244-4eca-a7df-9aaa5cac9287.png)
![image](https://user-images.githubusercontent.com/22729436/159794373-f2bf614a-ff64-4199-b3c1-0f91702ce06a.png)
& here's the error
![image](https://user-images.githubusercontent.com/22729436/159794797-65305afa-d90e-4ee3-89c3-1b1317dfb647.png)

**Comment by davidsmorais** [comment] 2022-03-23 21:10
In the case of audiosprites, which require to have the same name across different formats, this is also a blocker: 
![image](https://user-images.githubusercontent.com/22729436/159796093-9262899b-98d8-4446-b8f3-8d163c1c7758.png)
![image](https://user-images.githubusercontent.com/22729436/159796120-c3bde4c7-1927-4ffc-abe4-f33a1145cf39.png)

Basically, if we could add an option to suffix the variables with the file format, I think it would solve the issue

**Comment by WarrenJones** [comment] 2022-03-24 01:20
Oh,I got it,would be fixed within this week.

**Comment by WarrenJones** [comment] 2022-03-24 03:07
checkout the newest version,with readme about case 3,it's supported now!

**Comment by davidsmorais** [comment] 2022-03-24 21:09
Hey 👋 
Thanks for your switf action 👍 
I gave it a try and now it seems to be losing the file extension when importing: 
![image](https://user-images.githubusercontent.com/22729436/160010467-cb3ab8e0-d308-49a0-9e7f-aead0d8fbe06.png)
Relevant code:
![image](https://user-images.githubusercontent.com/22729436/160010589-99f70bfc-a892-4694-b0c7-e00fa3f160fb.png)

**Comment by WarrenJones** [comment] 2022-03-25 03:22
Thanks for your patient,I think this time would be fixed,just check the newest version again

**Comment by davidsmorais** [comment] 2022-03-25 15:53
Hey man 👋 
 Thanks again for comming up with a solution. 
 I gave it a shot and while it did indeed fixed the required errors, I now have the wrong file being loaded.
![image](https://user-images.githubusercontent.com/22729436/160154641-f88ab83f-3e88-4179-92e6-a686bb5c0004.png)

I'm still not 100% clear if this is something I'm doing wrong, but then again, I'm migrating from webpack, so I expected this to work almost out of the box 😆 
I'll post here if I manage to get a handle on the transpiled files

**Comment by davidsmorais** [comment] 2022-03-25 19:49
I've tried to move the `.default` to another part of the app, and I'm back to the first error.
Here's the relevant code:
![image](https://user-images.githubusercontent.com/22729436/160190995-036afcb4-669a-408f-8ef8-f32deb7623fa.png)
![image](https://user-images.githubusercontent.com/22729436/160191031-11017950-71bb-4484-bf9d-3dcc88e8d72e.png)
`ImagesHudShiftKeyFrames` is an empty enum

The error
![image](https://user-images.githubusercontent.com/22729436/160191127-0093f1dd-407e-4d70-8b75-340088236c34.png)

And my config: 
```js
 defineConfig({
  plugins: [
    requireTransform(
      (fileRegex = /.ts$|.tsx$|.png$|.css$|.json$|.ttf$|.ac3$|.ogg$|.m4a$|.mp3$/),
      (prefix = "vite_require_transform_"),
      (importPathHandler = (requirePath) => {
        return requirePath.replace(".", "_");
      })
    ),
  ],
...})
```

**Comment by WarrenJones** [comment] 2022-03-27 10:06
Thanks for your patitent again and I'm glad to solve the problem.I am not sure if it is the cause the problem of the plugin,Actually I can not understand the real problem that you propose this time,maybe you can  provide  a  minimal repo link that can reproduce the problem you ran into.

**Comment by davidsmorais** [comment] 2022-03-27 11:25
Hey again 👋 
Thanks for your help
The main problem I think is that since there are two files with the same, but different extensions, this plugin converts them to the same variable 👇 

![image](https://user-images.githubusercontent.com/22729436/160279212-f6a88164-6861-43f8-aac1-c70617539c5d.png)
![image](https://user-images.githubusercontent.com/22729436/160279204-8517746b-fdb3-41bd-9f11-21167ca35d0e.png)

I've moved away from the `require` statements and am trying a solution with `imports`, I'll lay down a repo where the issue can be replicated.

**Comment by WarrenJones** [comment] 2022-03-27 12:14
> Hey again 👋 Thanks for your help The main problem I think is that since there are two files with the same, but different extensions, this plugin converts them to the same variable 👇
> 
> ![image](https://user-images.githubusercontent.com/22729436/160279212-f6a88164-6861-43f8-aac1-c70617539c5d.png) ![image](https://user-images.githubusercontent.com/22729436/160279204-8517746b-fdb3-41bd-9f11-21167ca35d0e.png)
> 
> I've moved away from the `require` statements and am trying a solution with `imports`, I'll lay down a repo where the issue can be replicated.

I think the latest version can solve the problem of same file name,different extensions,I just wrote some test code,the default variable will be turn into fileName_extension_default format.

**Comment by WarrenJones** [comment] 2022-03-27 12:14
`typescript 
//same path,different extension
const testCaseA = require("caseA.extA?aaa");
const testCaseB = require("caseA.extB?bbb").default;

console.log("caseA", testCaseA)
console.log("caseB", testCaseB)`

will be turn into:
```typescript
import { default as _vite_plugin_require_transform_caseA_extB_bbb_default } from "caseA.extB?bbb";
import _vite_plugin_require_transform_caseA_extA_aaa from "caseA.extA?aaa";
//same path,different extension
const testCaseA = _vite_plugin_require_transform_caseA_extA_aaa;
const testCaseB = _vite_plugin_require_transform_caseA_extB_bbb_default;
console.log("caseA", testCaseA);
console.log("caseB", testCaseB);
```

**Closed** 2022-04-04 02:26 UTC

**Comment by WarrenJones** [comment] 2022-04-04 14:55
> Thanks for the help :)

you're welcome.It's my pleasure hahah to make sth to help anyone in the world,my friend
